### ISSUE TITLE
Dictionaries lab is completed: it is named dictionaries.py and in Week7 folder.

### ISSUE THREAD

**Issue by rleonard-matc** [madisoncollege-it-programs/python-scripting-rleonard-matc#8]

**Comment by cethenmc** [comment]
You may want to redo the last two in this, when it runs you get this error.  Technically, you are satisfying the request in # 6 and 7, but I would like you to do more gracefully.  Recording a 7 of 8 for now.  Please resubmit and reply to this message.

Traceback (most recent call last):
  File "./dictionaries.py", line 25, in <module>
    print(mydictionary["server10.testlab.com"])
KeyError: 'server10.testlab.com'

consider using an "in" statement in flow control.   I

**Comment by rleonard-matc** [comment]
I have I believe fixed this up for you.

**Comment by cethenmc** [comment]
Hi Rhett.  7 of 8 for now.  For the last two, use flow logic (instead of printing all of the keys).  Imagine you were in charge of a Server Farm with hundreds or thousands servers not in alphabetical/numerical order.  Use an "in" statement with an "if" for the last two.  Please reply to this Issue Ticket when you have submitted your change, or reply if you want to just keep the 7 and close the case.

Thanks.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by cethenmc** [comment]
Thanks for meeting today.  Please don't forget to reply to this GitHub Issue ticket once you have pushed your corrections to GitHub.  Thanks.  ~Chris

**Comment by cethenmc** [comment]
Corrections graded.  Full credit!  Nice work.
